// exportCSV(), Stitching_Manager_Pro_v16.html ~line 2339.
export function exportCSV(rows: Record<string, unknown>[], filename: string): void {
  if (!rows.length) return;
  const keys = Object.keys(rows[0]);
  const csv = [keys.join(",")]
    .concat(
      rows.map((r) => keys.map((k) => `"${String(r[k] ?? "").replace(/"/g, '""')}"`).join(","))
    )
    .join("\n");
  const a = document.createElement("a");
  a.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" }));
  a.download = `${filename}.csv`;
  a.click();
  URL.revokeObjectURL(a.href);
}

// printReport(), line ~2354.
export function printReport(title: string, tableHtml: string, shopName?: string, logoDataUrl?: string | null): void {
  const shopLabel = logoDataUrl
    ? `<img src="${logoDataUrl}" style="height:28px;width:28px;object-fit:contain;border-radius:4px;" alt="" /> ${shopName || "Fashion Flow"}`
    : `✂️ ${shopName || "Fashion Flow"}`;
  const html =
    `<!DOCTYPE html><html><head><title>${title}</title><style>body{font-family:sans-serif;padding:24px;color:#111;font-size:12px;}h2{font-size:17px;color:#18181B;margin-bottom:4px;}p{color:#94A3B8;font-size:11px;margin-bottom:18px;}table{width:100%;border-collapse:collapse;}th{background:#FAFAFA;padding:9px 11px;text-align:left;font-weight:300;color:#374151;border-bottom:2px solid #E4E4E7;font-size:11px;}td{padding:8px 11px;border-bottom:1px solid #F1F5F9;font-size:12px;}tr:nth-child(even){background:#FAFAFA;}.hdr{display:flex;justify-content:space-between;align-items:center;padding-bottom:14px;border-bottom:2px solid #F4F4F5;margin-bottom:20px;}.shop{display:flex;align-items:center;gap:8px;font-size:20px;font-weight:300;color:#18181B;letter-spacing:-0.04em;}.dt{font-size:11px;color:#94A3B8;}</style></head><body>` +
    `<div class="hdr"><div class="shop">${shopLabel}</div><div class="dt">Printed: ${new Date().toLocaleString("en-IN")}</div></div>` +
    `<h2>${title}</h2><p>Generated by Fashion Flow</p>${tableHtml}</body></html>`;
  const blob = new Blob([html], { type: "text/html" });
  const blobUrl = URL.createObjectURL(blob);
  const w = window.open(blobUrl, "_blank");
  if (w) {
    setTimeout(() => {
      w.print();
      setTimeout(() => URL.revokeObjectURL(blobUrl), 5000);
    }, 600);
  } else {
    window.location.href = blobUrl;
  }
}
