-- Projects & Tasks workspace (Zoho-Projects style) on top of the Targets module tables.
-- Run AFTER add_targets_module.sql. Idempotent. Every new table is service-role only (RLS on, no
-- policy for `authenticated`) — the API routes check the Targets permissions and licence first.

-- ── Readable ids shown in the UI (P-12, T-34) ──────────────────────────────
ALTER TABLE work_projects ADD COLUMN IF NOT EXISTS project_no BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- ── Task lists (the "Group By: Task List" sections inside a project) ───────
CREATE TABLE IF NOT EXISTS work_task_lists (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  project_id  UUID NOT NULL REFERENCES work_projects(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_work_task_lists_project ON work_task_lists (project_id, sort_order);

-- ── Phases (milestones) ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS work_phases (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  project_id  UUID NOT NULL REFERENCES work_projects(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  start_date  DATE,
  end_date    DATE,
  status      TEXT NOT NULL DEFAULT 'planned' CHECK (status IN ('planned', 'active', 'done')),
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_work_phases_project ON work_phases (project_id, sort_order);

-- ── Project members ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS work_project_members (
  project_id   UUID NOT NULL REFERENCES work_projects(id) ON DELETE CASCADE,
  employee_id  UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  added_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (project_id, employee_id)
);

-- ── Extra task fields ──────────────────────────────────────────────────────
ALTER TABLE work_tasks ADD COLUMN IF NOT EXISTS task_no BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE work_tasks ADD COLUMN IF NOT EXISTS task_list_id UUID REFERENCES work_task_lists(id) ON DELETE SET NULL;
ALTER TABLE work_tasks ADD COLUMN IF NOT EXISTS phase_id UUID REFERENCES work_phases(id) ON DELETE SET NULL;
ALTER TABLE work_tasks ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE work_tasks ADD COLUMN IF NOT EXISTS duration_hours NUMERIC(8,2);
ALTER TABLE work_tasks ADD COLUMN IF NOT EXISTS completion_pct INTEGER NOT NULL DEFAULT 0 CHECK (completion_pct BETWEEN 0 AND 100);
ALTER TABLE work_tasks ADD COLUMN IF NOT EXISTS reminder TEXT NOT NULL DEFAULT 'none';
ALTER TABLE work_tasks ADD COLUMN IF NOT EXISTS depends_on UUID[] NOT NULL DEFAULT '{}';
CREATE INDEX IF NOT EXISTS idx_work_tasks_task_list ON work_tasks (task_list_id);
CREATE INDEX IF NOT EXISTS idx_work_tasks_phase ON work_tasks (phase_id);

-- ── Comments + activity stream (one table; kind tells them apart) ──────────
CREATE TABLE IF NOT EXISTS work_task_events (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  project_id  UUID REFERENCES work_projects(id) ON DELETE CASCADE,
  task_id     UUID REFERENCES work_tasks(id) ON DELETE CASCADE,
  kind        TEXT NOT NULL DEFAULT 'comment' CHECK (kind IN ('comment', 'created', 'status', 'assigned', 'edited', 'time')),
  body        TEXT NOT NULL DEFAULT '',
  created_by  TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_work_task_events_task ON work_task_events (task_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_work_task_events_project ON work_task_events (project_id, created_at DESC);

-- ── Documents (links to files kept elsewhere: Drive, Dropbox, a photo link…) ─
CREATE TABLE IF NOT EXISTS work_documents (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  project_id  UUID REFERENCES work_projects(id) ON DELETE CASCADE,
  task_id     UUID REFERENCES work_tasks(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  url         TEXT NOT NULL,
  created_by  TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_work_documents_project ON work_documents (project_id);
CREATE INDEX IF NOT EXISTS idx_work_documents_task ON work_documents (task_id);

-- ── Time logs (feed the weekly timesheet) ──────────────────────────────────
CREATE TABLE IF NOT EXISTS work_time_logs (
  id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  task_id      UUID REFERENCES work_tasks(id) ON DELETE SET NULL,
  project_id   UUID REFERENCES work_projects(id) ON DELETE SET NULL,
  employee_id  UUID REFERENCES employees(id) ON DELETE SET NULL,
  log_date     DATE NOT NULL,
  hours        NUMERIC(5,2) NOT NULL CHECK (hours > 0 AND hours <= 24),
  note         TEXT NOT NULL DEFAULT '',
  created_by   TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_work_time_logs_employee_date ON work_time_logs (employee_id, log_date);
CREATE INDEX IF NOT EXISTS idx_work_time_logs_project ON work_time_logs (project_id, log_date);
CREATE INDEX IF NOT EXISTS idx_work_time_logs_task ON work_time_logs (task_id);

-- ── Lock the new tables to the service role ────────────────────────────────
ALTER TABLE work_task_lists       ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_phases           ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_project_members  ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_task_events      ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_documents        ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_time_logs        ENABLE ROW LEVEL SECURITY;
